// ⛔ This file is auto-generated, please don't edit it
export * from "discord.js"
export * from "./app.native.js"
export * from "./namespaces/labs.js"
export * from "./namespaces/date.js"
export * from "./namespaces/tools.js"
export * from "./namespaces/utils.js"
export * from "./namespaces/active.js"
export * from "./namespaces/tracker.js"
export * from "./namespaces/middlewares.js"

export * as Discord from "discord.js"
export * as middlewares from "./namespaces/middlewares.js"
export * as tracker from "./namespaces/tracker.js"
export * as active from "./namespaces/active.js"
export * as tools from "./namespaces/tools.js"
export * as utils from "./namespaces/utils.js"
export * as date from "./namespaces/date.js"
export * as labs from "./namespaces/labs.js"
