// ⛔ This file is auto-generated, please don't edit it
export * from "discord.js"
export * from "./app.native.ts"
export * from "./namespaces/ladder.ts"
export * from "./namespaces/labs.ts"
export * from "./namespaces/date.ts"
export * from "./namespaces/tools.ts"
export * from "./namespaces/active.ts"
export * from "./namespaces/tracker.ts"
export * from "./namespaces/middlewares.ts"
export * from "./namespaces/rating.ts"
export * from "./namespaces/point.ts"
export * from "./namespaces/fetcher.ts"
export * from "./namespaces/backup.ts"
export * from "./namespaces/automod.ts"
export * from "./namespaces/openai.ts"
export * from "./namespaces/emotes.ts"
export * from "./namespaces/remind.ts"
export * from "./namespaces/reply.ts"
export * from "./namespaces/coins.ts"

export * as Discord from "discord.js"
export * as ladder from "./namespaces/ladder.ts"
export * as middlewares from "./namespaces/middlewares.ts"
export * as tracker from "./namespaces/tracker.ts"
export * as active from "./namespaces/active.ts"
export * as tools from "./namespaces/tools.ts"
export * as date from "./namespaces/date.ts"
export * as labs from "./namespaces/labs.ts"
export * as rating from "./namespaces/rating.ts"
export * as point from "./namespaces/point.ts"
export * as fetcher from "./namespaces/fetcher.ts"
export * as backup from "./namespaces/backup.ts"
export * as automod from "./namespaces/automod.ts"
export * as openai from "./namespaces/openai.ts"
export * as emotes from "./namespaces/emotes.ts"
export * as remind from "./namespaces/remind.ts"
export * as reply from "./namespaces/reply.ts"
export * as coins from "./namespaces/coins.ts"
