name: Dev Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  node:
    name: Test on Node.js v22
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: [npm]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install package manager
        run: |
          if [ "${{ matrix.package-manager }}" != "npm" ]; then
            if [ "${{ matrix.package-manager }}" == "yarn" ]; then
              npm install -g yarn@latest
            else
              npm install -g ${{ matrix.package-manager }}@latest
            fi
          else
            echo "npm is already installed"
          fi

      - name: Copy lockfile
        run: |
          rm -f bun.lockb
          if [ "${{ matrix.package-manager }}" == "npm" ]; then
            cp lockfiles/package-lock.json ./
          elif [ "${{ matrix.package-manager }}" == "yarn" ]; then
            cp lockfiles/yarn.lock ./
          elif [ "${{ matrix.package-manager }}" == "pnpm" ]; then
            cp lockfiles/pnpm-lock.yaml ./
          fi

      - name: Install dependencies
        run: |
          if [ "${{ matrix.package-manager }}" == "npm" ]; then
            npm ci
            npm install @rollup/rollup-linux-x64-gnu
          elif [ "${{ matrix.package-manager }}" == "yarn" ]; then
            yarn install --frozen-lockfile
            yarn add @rollup/rollup-linux-x64-gnu
          elif [ "${{ matrix.package-manager }}" == "pnpm" ]; then
            pnpm install --frozen-lockfile
            pnpm add @rollup/rollup-linux-x64-gnu
          fi

      - name: Check typings
        run: npx tsc --noEmit

      - name: Build JS
        run: npx rimraf dist && npx rollup -c && node scripts/copy-keepers.js

      - name: Rebuild sqlite3
        run: |
          if [ "${{ matrix.package-manager }}" == "yarn" ]; then
            npm rebuild sqlite3
          else
            ${{ matrix.package-manager }} rebuild sqlite3
          fi

      - name: Start the bot
        run: node dist/index.test.js

